version: '3'
  services:
    mongo:
      container_name: veterinariaDB
      #volumes: 
      #- poke-vol:/data/db
      image: mongo:6.0.13
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MOGNO_PASSWORD}
      ports: 
      - 27017:27017
      command: ['--auth']
      restart : always